name: gray_fund
description: Pro Gray Fund App
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 网络请求
  http: ^1.2.0
  # 本地存储
  shared_preferences: ^2.2.2
  # Google AI
  google_generative_ai: ^0.2.0
  # 图标库
  cupertino_icons: ^1.0.2
  # 图表库
  fl_chart: ^0.66.0
  # 时间格式化
  intl: ^0.19.0
  
  # === 核心修复区 ===
  # 网页浏览器内核 (通用)
  webview_flutter: ^4.7.0
  # 网页版专用适配 (这里必须用新版本)
  webview_flutter_web: ^0.2.2
  # ================

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
